(Source native)
(Cfg_str project_name webmachine)
(Cfg_str project_slug webmachine)
(Cfg_str project_description"ocaml webmachine implementation")
(Cfg_str author_name"Alain Armand")
(Cfg_str github_username idkjs)
(Cfg_str syntax OCaml)